### ISSUE TITLE
"Open With" dialog keeps showing up?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [extraymond/zotero-snap#17]
This is a mirror of the following Zotero item: https://forums.zotero.org/discussion/82736/allow-opening-file

(I just posted there with a more thorough explanation, but it needs to go through mod approval...)

**Comment by extraymond** [comment]
@EricCousineau-TRI  Sorry for the late response. Here's some detail about why it is this way.

By design, snap prohibit access to resource not mutually granted by both the packager and the consumer. And must be delegated using the interface/slot architecture to ask for that specific resources.

Therefore, snap have no knowing and privilege to which app you have on your environment to view pdf files, and must ask it via xdg_open semantics. The open with dialog you saw was the action triggered by that xdg_open action on your platform, in my case I will get an kde's open_with dialog.

I understand that it's quite different than traditional linux apps, classic confinement will sometimes work and with enough test cases it might be a plausible solution, would you mind installing it via cli and force it to be classic?

snap install $snap --classic 
And if you can, please help us try with the candidate channel, it's using newer platform snap.

**Comment by EricCousineau-TRI** [comment]
Sorry for the delayed response, but thank you for the thorough explanation!
