### ISSUE TITLE
Issue accessing files

### ISSUE THREAD

**Issue by free41** [extraymond/zotero-snap#2]
I think there is an issue under preferences -> advanced -> linked attachment base directory. If you try to select a base directory the dialog box pops up but it when you select a folder it does not populate it in the base directory field.

**Comment by extraymond** [comment]
Thanks for reporting, can you please attach a screenshot and the output of your the following command: ```snap connections zotero-snap```?

**Comment by free41** [comment]
```
snap connections zotero-snap
Interface                 Plug                         Slot                             Notes
browser-support           zotero-snap:browser-support  :browser-support                 -
content[gnome-3-28-1804]  zotero-snap:gnome-3-28-1804  gnome-3-28-1804:gnome-3-28-1804  -
content[gtk-3-themes]     zotero-snap:gtk-3-themes     gtk-common-themes:gtk-3-themes   -
content[icon-themes]      zotero-snap:icon-themes      gtk-common-themes:icon-themes    -
content[sound-themes]     zotero-snap:sound-themes     gtk-common-themes:sound-themes   -
desktop                   zotero-snap:desktop          :desktop                         -
desktop-legacy            zotero-snap:desktop-legacy   :desktop-legacy                  -
gsettings                 zotero-snap:gsettings        :gsettings                       -
home                      zotero-snap:home             :home                            -
network-bind              zotero-snap:network-bind     :network-bind                    -
removable-media           zotero-snap:removable-media  -                                -
wayland                   zotero-snap:wayland          :wayland                         -
x11                       zotero-snap:x11              :x11                             -

```

**Comment by extraymond** [comment]
That does seem correct.
If you mean that the field looks weird, I think it's from zotero, both the .tar version and my snap version looks weird in some way.

**Comment by alanlivio** [comment]
Hello.
I have the same problem. See image dialog of the dialog bellow
![Screenshot from 2020-03-09 14-18-05](https://user-images.githubusercontent.com/604808/76240176-8c895d00-6211-11ea-9e5b-7d8bdc87cf52.png)

In my case, my zotero storage folder points to a Google Drive Folder. See bellow:
```
$ ls -lha zotero-snap/current/Zotero
drwxr-xr-x 6 alan alan 4,0K mar  9 14:17 .
drwxr-xr-x 7 alan alan 4,0K mar  9 14:01 ..
drwxr-xr-x 2 alan alan 4,0K mar  9 14:01 locate
drwx------ 2 alan alan 4,0K mar  9 14:17 pipes
lrwxrwxrwx 1 alan alan   32 mar  9 14:09 storage -> /home/alan/gdrive/zotero-storage
...
```

Any suggestions?

**Comment by extraymond** [comment]
@alanlivio 

Thans for your feedback.
Is your issue about not being able to see files across symlink, or just wondering why there is a popup dialogue? 
In the latter case, I believe it's because snap is requesting XDG_OPEN to redirect the call to a user preferred application. So it's a mechanism to restrict, therefore sandboxing, the application's footprint to the system.

**Comment by alanlivio** [comment]
Hello.
First, this popup is shown for any attached file including pdf and folders.

![image](https://user-images.githubusercontent.com/604808/76312497-f78a7080-62b1-11ea-87a1-644050ea42ce.png)
![image](https://user-images.githubusercontent.com/604808/76313982-bfd0f800-62b4-11ea-88d4-39fb92b7839d.png)

    "your issue about not being able to see files across symlink, 
    or just wondering why there is a popup dialogue?" 
It is the popup.
I initially believe that it is happening because of the symlink.
But seems that the popup appears using the symlink or not.
How to proceed?

**Comment by extraymond** [comment]
Well, the dialogue is a measure snap use to notify user that "you are handling this file to other app, are you sure you want to do this?", the same will happen if you install the firefox snap and try to open a downloaded picture. Hope that explains.

**Comment by alanlivio** [comment]
Thank you so much for your time to explain.
Do you know there is a way to avoid it?

**Comment by extraymond** [comment]
It might not be possible since it will require breaking out of the sandbox of snap, which is the major point of snap. Another possible route is to make this a classic snap where it will behave much or less like a deb. You can to build one if you think that's what you want. [relative into](https://snapcraft.io/docs/snap-confinement)

Thanks for sharing your feedback though. I will close this since I don't find it worth the risk to break sand-boxing for reducing clicks.
