### ISSUE TITLE
Is there an update planned soon?

### ISSUE THREAD

**Issue by ventolinmx** [extraymond/zotero-snap#44]
Hi

Zotero gives me an alert that there's an update available but i have no permission to install it. Tried sudo snap refresh zotero-snap but it returns that there are no updates available.

**Comment by pappasadrian** [comment]
same issue here :)

**Comment by hycinth22** [comment]
same +1

**Comment by pappasadrian** [comment]
FYI, I had to migrate to another install of zotero, since this snap is not being updated.
I followed the install instructions by zotero (see https://www.zotero.org/support/installation#linux ), and used the zotero-deb option: https://github.com/retorquere/zotero-deb
Seems like I was not the only one needing to migrate, see this thread for more: https://github.com/retorquere/zotero-deb/issues/93

**Comment by ventolinmx** [comment]
Thank you. Will that use the same database and configurations of my current Zotero Snap? Or do I have to move documents and configurations to the new zotero-deb installation?

**Comment by extraymond** [comment]
A new version(6.0.30) is updated to the stable channel. I'll try to work out with @maxsu  and see what can we do to improve the update cadence. Thanks for reporting.
