### ISSUE TITLE
[testing]  collecting feedback for migration to zotero 7.0

### ISSUE THREAD

**Issue by extraymond** [extraymond/zotero-snap#59]
### info

Recently, zotero has been released to 7.0. While the candidate repo provide up to date version of zotero, I would like to be extra cautious about how it'll effect users daily workflow.

### how you can help!

1. have proper backup of your 6.x version profile
2. switch to the candidate channel by `snap refresh zotero-snap --channel candidate`
3. use it like your normally would
4. try to interact with few of plugins that have stated to support zotero 7.0
5. post your experience below
6. if something you use is unfortunately tight to zotero 6, please also let me know

### follow-up actions

I plan to run this feedback for probably 2 weeks. If all goes well, I'll promote the candidate channel to stable so everyone can get zotero updated to the newest version.

If there's enough feedback to justify keeping the 6.0 version in parallel, I'll create a dedicated channel people who don't want to jump to the new version anytime soon.

**Comment by extraymond** [comment]
#57 related

**Comment by CasiN335** [comment]
A quick note from a new install of Kubuntu 24.04, the command to update to candidate channel is actually `snap refresh zotero-snap --channel candidate` and on first run it gave a libreoffice error but I have not even started libreoffice once yet. No error on second start of zotero.

The error is:
Installation could not be completed because an error occurred. Please ensure that LibreOffice is closed, and then restart Zotero.

NotAllowedError: Access was denied to the target file

**Comment by extraymond** [comment]
> A quick note from a new install of Kubuntu 24.04, the command to update to candidate channel is actually `snap refresh zotero-snap --channel candidate` and on first run it gave a libreoffice error but I have not even started libreoffice once yet. No error on second start of zotero.
> 
> The error is: Installation could not be completed because an error occurred. Please ensure that LibreOffice is closed, and then restart Zotero.
> 
> NotAllowedError: Access was denied to the target file

Thx for the feedback, that seems weird, I'll try to reproduce with a clean install.

**Comment by extraymond** [comment]
@CasiN335 
I can reproduce this.

I think I might know what's up! 
It's seems some kinds of automation is triggered on first run to maybe put that plugin to use with libreoffice.

Since it's under a snap the actual plugin path is /snap/zotero-snap/current/integration, maybe it's denied by accessing under that path.

However the plugin do seems to work if we:
1. copy the plugin to a directory where libreoffice can see, changing the owner to your user
2. install the plugin manually with libreoffice

I'll try to find what can be done with this libreoffice auto-integration.

**Comment by CasiN335** [comment]
Zotero seems to work fine with my plugins (actions and tagos for zotero, better bibtex for zotero, zotero reading list). Only thing I have noticed that does not work correctly is zotero links. Zotero opens when a link is clicked but it does not go to the place specified in the link, it only opens the application. Not sure if caused by something in Kubuntu or because it is a snap but the links work fine on Zotero 7 on Mint (it is not a snap) and Win.

**Comment by julienbr67** [comment]
hello thanks for your work
the snap zotero 7 seems to be working fine on my configuration : xubuntu 24.04 (ubuntu with xfce desktop), firefox connector and betterbibtex with auto export
Minor issue I noticed: the icon is the xfce placeholder on the panel instead of the zotero icon as it is correctly in the launcher

**Comment by extraymond** [comment]
It seems that only libreoffice detection has some issue with snap, other than that it works, I'll bump 7.x series to stable, hope nothings breaks (fingers crossed)
