### ISSUE TITLE
location of the default config directory

### ISSUE THREAD

**Issue by markusritschel** [extraymond/zotero-snap#8]
Hi there.
First of  all, thanks a lot for porting Zotero to Snap. I have a request/question though: Is it possible to set the default config directory to `$HOME/.zotero` and `$HOME/Zotero` as it is the case in the original program?
One reason is portability, another reason is that _snap_ deletes the content of `~/snap/zotero-snap/common/` when one uninstalls zotero-snap. Then the user looses all the settings, database etc.

**Comment by extraymond** [comment]
Thanks for reporting!  But I'm afraid the status would remain.

By design, snaps are not able to see hidden folders under $HOME, since it would break the sandboxing feature and allow other 
snaps to mess with the same file.

About the second point, it's correct that it will be cleaned by the snap daemon, what you can do is specify a zotero folder which is not under $HOME/.zotero nor $HOME/snap/zotero-snap. From the snap's perspective, it's just consuming an outside directory, which indicated that it might be used by non-snap programs. Hope this helps.
